services:
  practice-assets:
    build:
      context: .
      dockerfile: Dockerfile.practice-assets
    volumes:
      - ./client/src/static/practice:/output

  client-build:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client/dist:/output
