MAX_CURVE_JSON_BYTES = 8 * 1024 * 1024
MAX_CURVE_POINTS = 100_000
MAX_SHARE_DURATION_SECONDS = 10 * 60
MAX_SHARE_TITLE_LENGTH = 120
MIN_DELETE_TOKEN_LENGTH = 20
SHARE_ASSET_PURPOSE = "share"
UPLOAD_STATUS_PENDING = "pending"
UPLOAD_STATUS_READY = "ready"
