WECHAT_PROVIDER = "wechat"
WECHAT_CODE_EXCHANGE_URL = "https://api.weixin.qq.com/sns/jscode2session"
WECHAT_GRANT_TYPE = "authorization_code"
AUTH_TOKEN_BYTES = 48
AUTH_TOKEN_HASH_LENGTH = 64
WECHAT_REQUEST_TIMEOUT_SECONDS = 8
