export type AppIconName =
  | 'back'
  | 'calendar'
  | 'checkbox-empty'
  | 'checkbox-checked'
  | 'delete'
  | 'email'
  | 'favorite'
  | 'home'
  | 'headset'
  | 'info'
  | 'microphone'
  | 'music'
  | 'more'
  | 'pause'
  | 'play'
  | 'right'
  | 'save'
  | 'share'
  | 'statistics'
  | 'trend-up'
  | 'user'
  | 'waveform'

export type AppIconTone = 'accent' | 'primary' | 'muted' | 'white' | 'yellow'
