from pathlib import Path


OCTAVE_CONNECTION_EXERCISE_KEY = "connection-mum-octave"
OCTAVE_CONNECTION_VERSION = 1
OCTAVE_CONNECTION_TEMPO_BPM = 70
OCTAVE_CONNECTION_PATTERN = (0, 4, 7, 12, 12, 12, 12, 7, 4, 0)
OCTAVE_CONNECTION_COUNT_IN_BEATS = 4
OCTAVE_CONNECTION_NOTE_BEATS = 0.75
OCTAVE_CONNECTION_PHRASE_REST_BEATS = 1.0
PIANO_NOTE_DURATION_BEATS = 0.28
MIDI_TICKS_PER_BEAT = 480
MIDI_PIANO_PROGRAM = 0
MIDI_GUIDE_VELOCITY = 92
MIDI_COUNT_IN_VELOCITY = 62
MIDI_MINIMUM = 0
MIDI_MAXIMUM = 127
RENDER_SAMPLE_RATE = 44_100
OPUS_BITRATE = "48k"
ACCOMPANIMENT_LOUDNESS_FILTER = "loudnorm=I=-16:LRA=7:TP=-1.5"

MASTER_PIANO_RANGE = (48, 77)  # C3-F5
VOICE_PLAYBACK_RANGES: dict[str, tuple[int, int]] = {
    "male": (48, 72),   # C3-C5
    "female": (53, 77), # F3-F5
}

GENERATED_ASSET_DIRECTORY = Path("generated/practice")
